# Generated by Django 4.0.1 on 2022-01-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(blank=True, max_length=100)),
                ('Lastname', models.CharField(blank=True, max_length=100)),
                ('Course', models.CharField(blank=True, max_length=100)),
                ('Email', models.CharField(blank=True, max_length=100)),
                ('College', models.CharField(blank=True, max_length=100)),
                ('Year', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
